#!/bin/sh
set -ex

cd "$(dirname "$0")/.."

rm -rf stage/*
rm -rf dist/*
mkdir -p stage
mkdir -p dist
cp -a package.json package-lock.json src public views stage/
cd stage/
npm ci --production
rm -f package.json package-lock.json
advzip -a -3 -p ../dist/lambda.zip *
